version: '3.8'

services:
  mysql:
    container_name: "mysql_auth_container"
    image: "mysql:8.0.32"
    restart: always
    ports:
      - "3310:3306"
    expose:
      - "3310"
    volumes:
      - db_auth_test:/data
    environment:
      MYSQL_DATABASE: testauthdb
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass1
      MYSQL_ROOT_PASSWORD: root

#  adminer:
##    image: adminer:4.8.1
##    restart: always
##    ports:
##      - "9000:9000"

volumes:
  db_auth_test: