spring:
  datasource:
    url: jdbc:mysql://localhost:3310/testauthdb
    username: user1
    password: pass1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: false

access-refresh-token-path: "access-refresh-token-keys"

access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"

refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"

endpoints:
  public: "/api/auth/**"

logging:
  level:
    org:
      hibernate.sql: DEBUG
      springframework:
        security: DEBUG
        transaction.interceptor: DEBUG
